### ISSUE TITLE
Revisar SQL de la base y validar para entregar.

### ISSUE THREAD

**Issue by vinjatovix** [vinjatovix/booking-flights-app#2]
# Revisión del script para entregar.

@MattCo23, He subido la versión del SQL inicial a la rama dev con las correcciones que acordamos esta mañana con Santi.
De todas maneras échale un ojo para revisar que no me haya dejado nada atrás.

**Comment by MattCo23** [comment]
Todo correcto tío, no le veo nada que añadir
